### ISSUE TITLE
rabbitmq - integration test SendMessageRabbitmqIT is broken

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra-gateway#143]
Noticed here:
https://github.com/georchestra/georchestra-gateway/pull/142#issuecomment-2342077206

I first thought it was because console docker logging changed in newer versions of the image, as the test result relies on it, but turned out it might be related to a spring upgrade console-side:

```
--- console: 2024-09-11 09:27:12 SimpleMessageListenerContainer [WARN] Execution of Rabbit message listener failed, and no ErrorHandler has been set.
--- console: java.lang.NoSuchMethodError: 'byte[] org.springframework.amqp.core.MessageProperties.getCorrelationId()'
--- console: 	at org.springframework.amqp.rabbit.support.DefaultMessagePropertiesConverter.fromMessageProperties(DefaultMessagePropertiesConverter.java:107)
--- console: 	at org.springframework.amqp.rabbit.core.RabbitTemplate.doSend(RabbitTemplate.java:646)
--- console: 	at org.springframework.amqp.rabbit.core.RabbitTemplate$1.doInRabbit(RabbitTemplate.java:331)
--- console: 	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:600)
--- console: 	at org.springframework.amqp.rabbit.core.RabbitTemplate.send(RabbitTemplate.java:329)
--- console: 	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:358)
--- console: 	at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:346)
--- console: 	at org.georchestra.console.events.RabbitmqEventsSender.sendAcknowledgementMessageToGateway(RabbitmqEventsSender.java:30)
--- console: 	at org.georchestra.console.events.RabbitmqEventsListener.onMessage(RabbitmqEventsListener.java:67)
[...]
```

Maybe we are better off deactivating this test for now, as it breaks the build on something which has to be fixed console-side.

**Comment by pmauduit** [comment]
Also maybe we should make the test rely on the LDAP content (e.g. check if the user has been created) instead of parsing container's stdout.

**Comment by pmauduit** [comment]
I think  this one was due to a version bump in spring that we fixed, so yes we probably could.
