### ISSUE TITLE
Handle gateway crashes

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra-gateway#93]
Currently the gateway displays an unfriendly "Whitelabel Error Page" message when it crashes:

![image](https://github.com/georchestra/georchestra-gateway/assets/265319/d4e9e4c1-06fd-449d-be86-adeedde4a61c)

eg caused by:
```
Caused by: org.georchestra.ds.users.DuplicatedEmailException: there is a user with this email: test@provider.com
	at org.georchestra.ds.users.AccountDaoImpl.insert(AccountDaoImpl.java:148) ~[georchestra-ldap-account-management-23.1-SNAPSHOT.jar:na]
	at org.georchestra.gateway.accounts.admin.ldap.LdapAccountsManager.createInternal(LdapAccountsManager.java:94) ~[classes/:23.1-SNAPSHOT]
	at org.georchestra.gateway.accounts.admin.AbstractAccountsManager.createIfMissing(AbstractAccountsManager.java:64) ~[classes/:23.1-SNAPSHOT]
	at org.georchestra.gateway.accounts.admin.AbstractAccountsManager.lambda$getOrCreate$0(AbstractAccountsManager.java:40) ~[classes/:23.1-SNAPSHOT]
	at java.base/java.util.Optional.orElseGet(Unknown Source) ~[na:na]
```

What would be a better way of handling such errors ?

**Comment by pmauduit** [comment]
@edevosc2c already wrote a documentation to handle this:
https://github.com/georchestra/georchestra-gateway/blob/main/docs/custom-error-pages.adoc

but I think it would be better to provide default customized pages (in the datadir ?)

**Comment by fvanderbiest** [comment]
Awesome !
Yes, having default pages in the datadir sounds like a neat option

**Comment by pmauduit** [comment]
some templates are provided by default in the gateway, they can be overriden in the datadir following the documentation, I think we are all good here.
